name: LavaRun
main: me.arteon.lavarun.Main
version: 1.0
api-version: 1.17
author: Arteon
description: This is LavaRun plugin.
commands:
  setcenter:
    description: Setup center location.
  setpoint:
    description: Setup point A and B.
  setupinfo:
    description: Show info about setup.
